### ISSUE TITLE
Single smoochApp hosted on multiple heroku instances

### ISSUE THREAD

**Issue by qadir-genetech** [smooch/smooch-bot#20]
Hello.

Here is scenario I am facing. I have hosted two separate heroku instances with the single smooch app (i.e using same SMOOCH_APP_TOKEN, SMOOCH_KEY_ID and SMOOCH_SECRET for my both apps) 

`Note: Its our business need to use the single smooch app deployed on multiple heroku instances`

![image](https://user-images.githubusercontent.com/14326497/52773271-5f916780-305c-11e9-87f2-8412edba5c2a.png)

Now when both server starts running, both create a new webhook (i.e named /webhook) on my smooch app dashboard with two different targets as shown in following image

![image](https://user-images.githubusercontent.com/14326497/52774327-c1eb6780-305e-11e9-88ba-a11a5e3d147c.png)

Now what happens when I send any message to my Bot from any appUser (i.e web) the bot reply  received/appears twice on appUser screen. like as shown in image below.

![image](https://user-images.githubusercontent.com/14326497/52775083-9ff2e480-3060-11e9-87e1-e871f1add2bd.png)

**Question:**
How to control this? I want my bot should send response once.

**Comment by alavers** [comment]
You need to store some user-specific state somewhere your two webhook endpoints can see so that they know whether or not they're supposed to respond. You can put this state in your own database, or store appUser metadata.

Closing, as this is not an issue specifically related to `smooch-bot`.

(By the way, this "multi-webhook switchboard" use case is something we're currently working on productizing however I can't make any date promses)
